### 01- Маппинг Отправки активных кредитных продуктов
GET http://localhost:8083/credit-products

### 02 - Маппинг Просмотра активного кредитного продукта
GET http://localhost:8083/credit-products/1

### 03 - Маппинг Создания заявки на кредит
POST http://localhost:8083/loan-applications
Content-Type: application/json
clientId: 0799f8b8-729d-4818-b1ba-5e64f88f6d03

{
  "productId": 1,
  "amountRequested": 100000.00,
  "periodMonths": 12,
  "creationDate": "2023-01-01",
  "monthlyIncome": 5000.00,
  "monthlyExpenditure": 3000.00,
  "employerIdentificationNumber": "123-45-6789"
}

### 04 - Маппинг Получения данных о кредитных заявках
GET http://localhost:8083/loan-applications
clientId: 0799f8b8-729d-4818-b1ba-5e64f88f6d03


### 05 - Маппинг Отзыва кредитной заявки
PATCH http://localhost:8083/loan-applications
Content-Type: application/json
clientId: 0799f8b8-729d-4818-b1ba-5e64f88f6d03

{
  "id": 1,
  "status": "REJECT_BY_CLIENT"
}

### 06 - Маппинг Подтверждения кредитной заявки
PATCH http://localhost:8083/loan-applications
Content-Type: application/json
clientId: 0799f8b8-729d-4818-b1ba-5e64f88f6d03

{
  "id": 1,
  "status": "APPROVED_BY_CLIENT"
}

###==CREDIT CARD===

###block
PATCH http://localhost:8083/api/v1/credit-cards
Content-Type: application/json

{
  "cardNumber": "1234567891234567",
  "cardStatus": "ACTIVE"
}

###pin
POST http://localhost:8083/api/v1/credit-cards/code
Content-Type: application/json

{
  "cardNumber": "1234567891234567",
  "newPin": "4321"
}

###limit
PATCH http://localhost:8080/api/v1/credit-cards/limit
Content-Type: application/json

{
  "cardNumber": "1234007891234567",
  "transactionLimit": 100
}

###getById
GET http://localhost:8083/api/v1/credit-cards/1234567891234567

###getAll
GET http://localhost:8083/api/v1/credit-cards?clientId=0799f8b8-729d-4818-b1ba-5e64f88f6d03

###==CREDIT===

###getAll
GET http://localhost:8083/api/v1/credits?clientId=0799f8b8-729d-4818-b1ba-5e64f88f6d03

### schedule
GET http://localhost:8083/api/v1/credits/1/schedule
clientId: 0799f8b8-729d-4818-b1ba-5e64f88f6d03

### agreement
GET http://localhost:8083/api/v1/credits/1/details

