###==CREDIT ORDER===

### create
POST http://localhost:8080/api/v1/loan-applications
Content-Type: application/json
clientId: 0799f8b8-729d-4818-b1ba-5e64f88f6d03

{
  "productId": 2,
  "amountRequested": 100000.00,
  "periodMonths": 12,
  "creationDate": "2023-01-01",
  "monthlyIncome": 5000.00,
  "monthlyExpenditure": 3000.00,
  "employerIdentificationNumber": "123-45-6789"
}

### getOrdersByClienId
GET http://localhost:8080/api/v1/loan-applications
clientId: 0799f8b8-729d-4818-b1ba-5e64f88f6d03

### reject
PATCH http://localhost:8080/api/v1/loan-applications
Content-Type: application/json
clientId: 0799f8b8-729d-4818-b1ba-5e64f88f6d03

{
  "id": 1,
  "status": "REJECT_BY_CLIENT"
}

### approved
PATCH http://localhost:8080/api/v1/loan-applications
Content-Type: application/json
clientId: 0799f8b8-729d-4818-b1ba-5e64f88f6d03

{
  "id": 2,
  "status": "APPROVED_BY_CLIENT"
}

###==CREDIT CARD===

###block
PATCH http://localhost:8083/api/v1/credit-cards
Content-Type: application/json

{
  "cardNumber": "1234567891234567",
  "cardStatus": "BLOCKED"
}

###pin
POST http://localhost:8080/api/v1/credit-cards/code
Content-Type: application/json

{
  "cardNumber": "1234567800234567",
  "newPin": "4321"
}

###limit
PATCH http://localhost:8080/api/v1/credit-cards/limit
Content-Type: application/json

{
  "cardNumber": "1234007891234567",
  "transactionLimit": 100
}

###==CREDIT===

### schedule
GET http://localhost:8080/api/v1/credits/1/schedule
clientId: 0799f8b8-729d-4818-b1ba-5e64f88f6d00

### agreement
GET http://localhost:8080/api/v1/credits/100/details