include:
  - project: 'rvaliev/devops'
    ref: main
    file:
      - 'templates/build-template.yml'
      - 'templates/deploy-template.yml'


stages:
  - build
  - deploy
  - cleanup

variables:
  PROJECT: astlink
  APP: credit-service


docker-build:
  stage: build
  extends: .kaniko-build-template
  only:
    - develop

multi-deploy:
  stage: deploy
  tags:
    - shell-dev
  extends: .deploy-template
  only:
    - develop

cleanup:
  stage: cleanup
  tags:
    - shell-dev
  script:
     - docker system prune -f --filter "label!=keep"
  when: always
  only:
    - develop
