version: '3.7'
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=credit
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'
#    volumes:
#      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro