version: '3.6'

services:

  credit-service:
    image: '$AND_DOCKER_REGISTRY_NAME/$PROJECT-$APP:$CI_COMMIT_BRANCH'
    container_name: $APP-$CI_COMMIT_BRANCH
    restart: always
    ports:
      - "8086:8086"
    networks:
      - astlink
    environment:
      eureka.instance.hostname: eureka-service-develop
      eureka.client.serviceUrl.defaultZone: http://eureka-service-develop:8761/eureka


networks:
  astlink:
    external: true

volumes:
  data-postgres:
