version: '3.6'

services:

  credit-service:
    image: '$AND_DOCKER_REGISTRY_NAME/$PROJECT-$APP:$CI_COMMIT_BRANCH'
    container_name: $APP-$CI_COMMIT_BRANCH
    restart: always
    networks:
      - astlink


networks:
  astlink:
    external: true