spring:
  profiles:
    active: "dev"
  application:
    name: creditservice
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
springdoc:
  swagger-ui:
    path: credit-swagger
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service-develop:8761/eureka

---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://postgresDB:5432/credit}
    username: ${DB_USER:verification_service_developer}
    password: ${DB_PASSWORD:Mgy4Xn1Wkeul}
  #далее прописано для kafka
  kafka:
    bootstrap-servers: ${KF_URL:kafka:9092}
    consumer:
      group-id: CreditGroupId
      auto-offset-reset: latest
    topics:
      update-status-from: master_to_credit_update_status_card
      update-status-in: credit_to_master_update_status_card
      update-pin: credit_to_master_update_pin
server:
  port: 8086

---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/credit
    username: credit_service_developer
    password: Mgy4Xn1Wkeul
    #далее прописано для kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: CreditGroupId
      auto-offset-reset: latest
    topics:
      update-status-from: master_to_credit_update_status_card
      update-status-in: credit_to_master_update_status_card
      update-pin: credit_to_master_update_pin
server:
  port: 8083
